parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            Symfony\Component\Workflow\StateMachine $trafficLightStateMachine: '@state_machine.traffic_light'
            Symfony\Component\Workflow\StateMachine $pullRequestStateMachine: '@state_machine.pull_request'
            Symfony\Component\Workflow\StateMachine $signupStateMachine: '@state_machine.signup'
            Symfony\Component\Workflow\Workflow $articleWorkflow: '@workflow.article'

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

sensio_framework_extra:
    router:
        annotations: false

framework:
    workflows:
        traffic_light:
            supports: App\Entity\TrafficLight
            type: state_machine
            marking_store:
                type: 'method'
                property: 'state'
            places:
                - green
                - yellow
                - red
            transitions:
                to_green:
                    from: yellow
                    to: green
                to_yellow:
                    from: [ green, red ]
                    to: yellow
                to_red:
                    from: yellow
                    to: red

        pull_request:
            supports: App\Entity\PullRequest
            type: state_machine
            marking_store:
                type: 'method'
                property: 'state'
            places:
                - preSubmitted
                - open
                - closed
                - locked
                - merged
            transitions:
                submit:
                    from: preSubmitted
                    to: open
                close:
                    from: open
                    to: closed
                reopen:
                    from: [closed, locked]
                    to: open
                lock:
                    from: [open, closed]
                    to: locked
                merge:
                    from: open
                    to: merged
